### ISSUE TITLE
Unable to find objects inside a canvas without recttransform component

### ISSUE THREAD

**Issue by robert-altom** [robert-altom/test#780]
We have objects inside a canvas which does not have recttransform component like particle system.

---
<sub>You can find the original issue from GitLab [here](https://gitlab.com/altom/altunity/altunitytester/-/issues/110).</sub>

**Comment by robert-altom** [comment]
Yeah, I hope we will release the next version as soon as possible so others won't run into this issue.

**Comment by robert-altom** [comment]
Sure @robert\_poienar, With AltunityRunner.cs changes,We need AltUnityObjectAction.cs changes also to avoid compilation errors.

Thought this will be useful to others who run into same issue

**Comment by robert-altom** [comment]
Glad it worked and sorry for inconvenience. If you find any other problems don't hesitate to write another issue. So if you are ok can I close this issue?

**Comment by robert-altom** [comment]
Thganks @robert\_poienar, after replacing AltUnityRunner.cs file it worked.

**Comment by robert-altom** [comment]
We didn't change on the python part anything for this. We only change on the server side so if you change what is on the version 1.2.2 in `AltUnityRunner.cs` with what is on the master and rebuild the game it should work.

**Comment by robert-altom** [comment]
@robert\_poienar We are on 1.2.2, still getting Received data was: error:unknownError;System.NullReferenceException: Object reference not set to an instance of an object, when try to find objects without recttransform.

Requirement already satisfied: altunityrunner in /usr/local/lib/python2.7/site-packages (1.2.2)

**Comment by robert-altom** [comment]
It was a complicated situation why we did that fix on the master. The short story is that it was mistake from my part on how this situation was handled and we will mention this fix and document it for the next version. But it works with 1.2.2.

**Comment by robert-altom** [comment]
Thanks @robert\_poienar, will try to take the latest source code from master and try.

what is the fix for it ? 

Also, with which release it will go ?

**Comment by robert-altom** [comment]
Yeah, this is a bug that we also noticed. It was fixed but forgot to document it(my fault). The version that it is on the master has the fix. So you should be able to take that version. Let me know if you have any problem with taking the code from master or after that you still have problems.
